source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/smarttab.kak" %{
    set-option global softtabstop 4
}
plug "andreyorst/fzf.kak" %{
	map global normal <c-p> ': fzf-mode<ret>'
}


set-option global grepcmd 'ag --column'
set global ui_options ncurses_assistant=none

#add-highlighter global/ number-lines
hook global WinCreate ^[^*]+$ %{
	add-highlighter window/ number-lines -hlcursor -separator ' '
	addhl global/ regex '\h+$' 0:default,red
    addhl global/ regex \b(TODO|FIXME|XXX|NOTE)\b 0:default+rb
    addhl global/ show-matching
    addhl global/ dynregex '%reg{/}' 0:+u
	addhl global/ dynregex '%opt{curword}' 0:+b
	}


map global insert <tab> '<a-;><gt>'
map global insert <s-tab> '<a-;><lt>'
hook global InsertCompletionShow .* %{
    try %{
        # this command temporarily removes cursors preceded by whitespace;
        # if there are no cursors left, it raises an error, does not
        # continue to execute the mapping commands, and the error is eaten
        # by the `try` command so no warning appears.
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
    }
}
hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}

map global normal <space> ,
map global normal , <space>
map global normal -docstring 'comment line' '#' :comment-line<ret>
map global normal -docstring 'comment block' '<a-#>' :comment-block<ret>

map -docstring 'paste after' global user p '<a-!>xsel --output --clipboard<ret>'
map -docstring 'paste before' global user P '!xsel --output --clipboard<ret>'
hook global NormalKey y|d|c %{ nop %sh{
  printf %s "$kak_main_reg_dquote" | xsel --input --clipboard
}}


declare-option str modeline_pos_percent
hook global WinCreate .* %{
    hook window NormalIdle .* %{ evaluate-commands %sh{
        echo "set window modeline_pos_percent '$(($kak_cursor_line * 100 / $kak_buf_line_count))'"
    } }
}

set global modelinefmt '%val{cursor_line}:%val{cursor_char_column}(%opt{modeline_pos_percent}%%) {{context_info}} {{mode_info}} %val{bufname} - %val{client}@[%val{session}]'